apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: email-backend
  template:
    metadata:
      labels:
        app: email-backend
    spec:
      containers:
      - image: boblancer/email-backend
        name: email-backend
        ports:
        - containerPort: 80